export function getEnrollmentMessage({ hasPolicy, submitting, success }) {
  if (submitting) {
    return { tone: 'info', message: 'Activating your coverage...' };
  }

  if (success) {
    return { tone: 'success', message: 'Coverage activated. Your premium will be generated by the weekly pricing cycle.' };
  }

  if (hasPolicy) {
    return { tone: 'success', message: 'Your account already has active coverage.' };
  }

  return { tone: 'info', message: 'Activate coverage to start weekly pricing and automatic payout eligibility.' };
}
