import { useQuery } from '@tanstack/react-query';
import { View } from 'react-native';
import { DataListItem } from '../components/DataListItem';
import { EmptyState } from '../components/EmptyState';
import { InfoPanel } from '../components/InfoPanel';
import { LoadingState } from '../components/LoadingState';
import { NoticeStrip } from '../components/NoticeStrip';
import { ScreenShell } from '../components/ScreenShell';
import { SectionTitle } from '../components/SectionTitle';
import { StatCard } from '../components/StatCard';
import { useAuth } from '../features/auth/AuthContext';
import { api } from '../lib/api/client';
import { theme } from '../lib/theme/theme';

export function HomeScreen() {
  const { user } = useAuth();
  const coverageQuery = useQuery({
    queryKey: ['policy-coverage'],
    queryFn: () => api.policies.getCoverage()
  });
  const currentPremiumQuery = useQuery({
    queryKey: ['billing-current'],
    queryFn: () => api.billing.getCurrent()
  });
  const latestPayoutQuery = useQuery({
    queryKey: ['payout-latest'],
    queryFn: () => api.payouts.getLatest()
  });
  const reviewStatusQuery = useQuery({
    queryKey: ['policy-review-status'],
    queryFn: () => api.policies.getReviewStatus()
  });

  const isLoading =
    coverageQuery.isLoading ||
    currentPremiumQuery.isLoading ||
    latestPayoutQuery.isLoading ||
    reviewStatusQuery.isLoading;

  const coverage = coverageQuery.data?.data || null;
  const currentPremium = currentPremiumQuery.data?.data || null;
  const latestPayout = latestPayoutQuery.data?.data || null;
  const reviewItems = reviewStatusQuery.data?.data || [];
  const hasReviewHold = Boolean(reviewItems?.length || latestPayout?.status === 'held');

  if (isLoading) {
    return (
      <ScreenShell
        eyebrow="Worker Dashboard"
        title="GIGSurance"
        description="Worker-facing home for coverage, weekly premium, and payout status."
      >
        <LoadingState label="Loading your worker dashboard" />
      </ScreenShell>
    );
  }

  return (
    <ScreenShell
      eyebrow="Worker Dashboard"
      title="GIGSurance"
      description="Worker-facing home for coverage, weekly premium, and payout status."
    >
      <NoticeStrip
        tone={hasReviewHold ? 'warning' : 'info'}
        text={
          hasReviewHold
            ? 'A payout or review item may need attention. The latest status is reflected below in worker-safe language.'
            : 'This is your primary worker dashboard for coverage status, this week’s premium, and latest payout outcome.'
        }
      />
      <View style={{ gap: theme.spacing.lg }}>
        <StatCard
          eyebrow="Current Coverage"
          title={coverage?.status || user?.currentPolicy?.status || 'Unknown'}
          value={coverage?.status === 'active' ? 'Protected' : coverage?.status ? coverage.status : 'Not Active'}
          note="Coverage status is driven by your current policy and weekly protection state."
          tone={coverage?.status === 'active' ? 'success' : 'warning'}
        />
        <StatCard
          eyebrow="Weekly Premium"
          title={currentPremium?.status || 'Current'}
          value={currentPremium ? `Rs ${currentPremium.finalPremiumInr ?? 0}` : 'Not Generated'}
          note="Premiums are generated by the backend weekly pricing cycle. This app shows the current worker-visible amount only."
          tone="primary"
        />
        <StatCard
          eyebrow="Latest Payout"
          title={latestPayout?.status || 'No Recent Payout'}
          value={latestPayout ? `Rs ${latestPayout.finalPayoutInr ?? 0}` : 'No Payout Yet'}
          note="Latest payout status reflects backend decisions such as approved, held, failed, or not eligible."
          tone={latestPayout?.status === 'approved' ? 'success' : latestPayout?.status === 'held' ? 'warning' : 'info'}
        />
      </View>
      <SectionTitle eyebrow="Next Phase" title="Worker Summary Surface" meta="This screen will become the main at-a-glance dashboard." />
      <InfoPanel
        title="Coverage Snapshot"
        body={`Coverage is ${coverage?.status || 'unknown'}. ${
          hasReviewHold
            ? 'A review or hold-related state exists, and the worker-facing summary is shown below.'
            : 'No open review or hold state is currently visible on this account.'
        }`}
        tone={hasReviewHold ? 'warning' : 'info'}
        badgeLabel={hasReviewHold ? 'Review Aware' : 'Clear'}
      />
      {coverage || currentPremium || latestPayout ? (
        <View style={{ gap: theme.spacing.md }}>
          <SectionTitle eyebrow="Worker Details" title="Current Status" meta="Readable account-level coverage and payout context." />
          <DataListItem
            label="Protection Active"
            value={coverage?.status === 'active' ? 'Yes' : 'No'}
            meta="Protection is considered active when your current policy is active."
            tone={coverage?.status === 'active' ? 'success' : 'warning'}
            badgeLabel={coverage?.status || 'unknown'}
          />
          <DataListItem
            label="Current Weekly Premium"
            value={currentPremium ? `Rs ${currentPremium.finalPremiumInr ?? 0}` : 'Unavailable'}
            meta={currentPremium?.confidenceBand ? `Confidence band: ${currentPremium.confidenceBand}` : 'No current premium decision available.'}
            tone="primary"
            badgeLabel={currentPremium?.status || 'pending'}
          />
          <DataListItem
            label="Latest Payout Status"
            value={latestPayout?.status || 'No recent payout'}
            meta={
              latestPayout
                ? `Recommended trust action: ${latestPayout.recommendedTrustAction || 'n/a'}`
                : 'Payout history will appear here when a disruption leads to a decision.'
            }
            tone={latestPayout?.status === 'approved' ? 'success' : latestPayout?.status === 'held' ? 'warning' : 'neutral'}
            badgeLabel={latestPayout?.status || 'empty'}
          />
        </View>
      ) : (
        <EmptyState
          title="No live worker data yet"
          body="Your dashboard will populate as premium decisions and payout decisions become available."
        />
      )}
    </ScreenShell>
  );
}
