import { useQuery } from '@tanstack/react-query';
import { View } from 'react-native';
import { DataListItem } from '../components/DataListItem';
import { EmptyState } from '../components/EmptyState';
import { ErrorState } from '../components/ErrorState';
import { InfoPanel } from '../components/InfoPanel';
import { LoadingState } from '../components/LoadingState';
import { NoticeStrip } from '../components/NoticeStrip';
import { ScreenShell } from '../components/ScreenShell';
import { SectionTitle } from '../components/SectionTitle';
import { StatCard } from '../components/StatCard';
import { useAuth } from '../features/auth/AuthContext';
import { api, getErrorMessage, isUnauthorizedError } from '../lib/api/client';
import { theme } from '../lib/theme/theme';
import {
  formatCurrencyInr,
  formatStatusLabel,
  getStatusTone
} from '../lib/utils/format';

export function HomeScreen() {
  const { user, logout } = useAuth();
  const dashboardQuery = useQuery({
    queryKey: ['worker-dashboard'],
    queryFn: () => api.users.getDashboard()
  });

  const isLoading = dashboardQuery.isLoading;

  const dashboard = dashboardQuery.data?.data || {};
  const coverage = dashboard.coverage || null;
  const currentPremium = dashboard.currentPremium || null;
  const latestPayout = dashboard.latestPayout || null;
  const hasReviewHold = Boolean(dashboard.reviewSummary?.hasOpenReview || latestPayout?.status === 'held');

  if (isLoading) {
    return (
      <ScreenShell
        eyebrow="Worker Dashboard"
        title="GIGSurance"
        description="Worker-facing home for coverage, weekly premium, and payout status."
      >
        <LoadingState label="Loading your worker dashboard" />
      </ScreenShell>
    );
  }

  if (dashboardQuery.isError) {
    return (
      <ScreenShell
        eyebrow="Worker Dashboard"
        title="GIGSurance"
        description="Worker-facing home for coverage, weekly premium, and payout status."
      >
        <ErrorState
          title={isUnauthorizedError(dashboardQuery.error) ? 'Session expired' : 'Dashboard unavailable'}
          body={
            isUnauthorizedError(dashboardQuery.error)
              ? 'Your session is no longer valid. Sign in again to continue.'
              : getErrorMessage(dashboardQuery.error, 'The backend is temporarily unavailable or local services are not fully running.')
          }
          actionLabel={isUnauthorizedError(dashboardQuery.error) ? 'Log Out' : 'Retry'}
          onAction={isUnauthorizedError(dashboardQuery.error) ? logout : () => dashboardQuery.refetch()}
        />
      </ScreenShell>
    );
  }

  return (
    <ScreenShell
      eyebrow="Worker Dashboard"
      title="GIGSurance"
      description="Worker-facing home for coverage, weekly premium, and payout status."
    >
      <NoticeStrip
        tone={hasReviewHold ? 'warning' : 'info'}
        text={
          hasReviewHold
            ? 'A payout or review item may need attention. The latest status is reflected below in worker-safe language.'
            : 'This is your primary worker dashboard for coverage status, this week’s premium, and latest payout outcome.'
        }
      />
      <View style={{ gap: theme.spacing.lg }}>
        <StatCard
          eyebrow="Current Coverage"
          title={formatStatusLabel(coverage?.status || user?.currentPolicy?.status || 'Unknown')}
          value={coverage?.status === 'active' ? 'Protected' : coverage?.status ? formatStatusLabel(coverage.status) : 'Not Active'}
          note="Coverage status is driven by your current policy and weekly protection state."
          tone={getStatusTone(coverage?.status)}
        />
        <StatCard
          eyebrow="Weekly Premium"
          title={formatStatusLabel(currentPremium?.status || 'Current')}
          value={currentPremium ? formatCurrencyInr(currentPremium.finalPremiumInr) : 'Not Generated'}
          note="Premiums are generated by the backend weekly pricing cycle. This app shows the current worker-visible amount only."
          tone="primary"
        />
        <StatCard
          eyebrow="Latest Payout"
          title={formatStatusLabel(latestPayout?.status || 'No Recent Payout')}
          value={latestPayout ? formatCurrencyInr(latestPayout.finalPayoutInr) : 'No Payout Yet'}
          note="Latest payout status reflects backend decisions such as approved, held, failed, or not eligible."
          tone={getStatusTone(latestPayout?.status)}
        />
      </View>
      <SectionTitle eyebrow="Next Phase" title="Worker Summary Surface" meta="This screen will become the main at-a-glance dashboard." />
      <InfoPanel
        title="Coverage Snapshot"
        body={`Coverage is ${coverage?.status || 'unknown'}. ${
          hasReviewHold
            ? 'A review or hold-related state exists, and the worker-facing summary is shown below.'
            : 'No open review or hold state is currently visible on this account.'
        }`}
        tone={hasReviewHold ? 'warning' : 'info'}
        badgeLabel={hasReviewHold ? 'Review Aware' : 'Clear'}
      />
      {coverage || currentPremium || latestPayout ? (
        <View style={{ gap: theme.spacing.md }}>
          <SectionTitle eyebrow="Worker Details" title="Current Status" meta="Readable account-level coverage and payout context." />
          <DataListItem
            label="Protection Active"
            value={coverage?.status === 'active' ? 'Yes' : 'No'}
            meta="Protection is considered active when your current policy is active."
            tone={getStatusTone(coverage?.status)}
            badgeLabel={formatStatusLabel(coverage?.status || 'unknown')}
          />
          <DataListItem
            label="Current Weekly Premium"
            value={currentPremium ? formatCurrencyInr(currentPremium.finalPremiumInr) : 'Unavailable'}
            meta={currentPremium?.confidenceBand ? `Confidence band: ${currentPremium.confidenceBand}` : 'No current premium decision available.'}
            tone="primary"
            badgeLabel={formatStatusLabel(currentPremium?.status || 'pending')}
          />
          <DataListItem
            label="Latest Payout Status"
            value={formatStatusLabel(latestPayout?.status || 'No recent payout')}
            meta={
              latestPayout
                ? `Recommended trust action: ${latestPayout.recommendedTrustAction || 'n/a'}`
                : 'Payout history will appear here when a disruption leads to a decision.'
            }
            tone={getStatusTone(latestPayout?.status)}
            badgeLabel={formatStatusLabel(latestPayout?.status || 'empty')}
          />
        </View>
      ) : (
        <EmptyState
          title="No live worker data yet"
          body="Your dashboard will populate as premium decisions and payout decisions become available."
        />
      )}
    </ScreenShell>
  );
}
