import { useState } from 'react';
import { View } from 'react-native';
import { ActionCard } from '../components/ActionCard';
import { DataListItem } from '../components/DataListItem';
import { NoticeStrip } from '../components/NoticeStrip';
import { ScreenShell } from '../components/ScreenShell';
import { SectionTitle } from '../components/SectionTitle';
import { StatusBadge } from '../components/StatusBadge';
import { useAuth } from '../features/auth/AuthContext';
import { getEnrollmentMessage } from '../features/policies/enrollmentState';
import { theme } from '../lib/theme/theme';

export function PolicyEnrollScreen() {
  const { user, enrollPolicy, getErrorMessage } = useAuth();
  const initial = getEnrollmentMessage({ hasPolicy: Boolean(user?.currentPolicy), submitting: false, success: false });
  const [message, setMessage] = useState(initial.message);
  const [tone, setTone] = useState(initial.tone);
  const [submitting, setSubmitting] = useState(false);

  async function handleEnroll() {
    setSubmitting(true);
    const progress = getEnrollmentMessage({ hasPolicy: Boolean(user?.currentPolicy), submitting: true, success: false });
    setTone(progress.tone);
    setMessage(progress.message);

    try {
      await enrollPolicy();
      const success = getEnrollmentMessage({ hasPolicy: true, submitting: false, success: true });
      setTone(success.tone);
      setMessage(success.message);
    } catch (error) {
      setTone('danger');
      setMessage(getErrorMessage(error, 'Unable to activate coverage right now.'));
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <ScreenShell
      eyebrow="Coverage Activation"
      title="Activate GIGSurance"
      description="Coverage is simple by design. Activate your policy, then the backend handles weekly premium generation and payout eligibility."
      rightSlot={<StatusBadge tone="primary" label="Required" />}
    >
      <NoticeStrip tone={tone} text={message} />

      <ActionCard
        eyebrow="Current Worker"
        title="Policy activation is the next step"
        body="There is no complex checkout flow in this version. Once you activate coverage, the backend weekly pricing cycle will generate your current premium."
        actionLabel={submitting ? 'Activating...' : 'Activate Coverage'}
        onPress={handleEnroll}
      />

      <View style={{ gap: theme.spacing.md }}>
        <SectionTitle eyebrow="What This Means" title="Worker Coverage Summary" meta="This reflects current backend behavior only." />
        <DataListItem
          label="Linked Worker"
          value={user?.linkedWorker?.platformDriverId || 'Worker linked'}
          meta={`${user?.linkedWorker?.platformName || 'platform'} worker in ${user?.linkedWorker?.city || 'your city'}`}
          tone="success"
          badgeLabel="Linked"
        />
        <DataListItem
          label="Policy Status"
          value={user?.currentPolicy?.status ? `Already ${user.currentPolicy.status}` : 'Not enrolled yet'}
          meta="If you are not enrolled, activating coverage creates your primary policy."
          tone={user?.currentPolicy ? 'success' : 'warning'}
          badgeLabel={user?.currentPolicy ? 'Enrolled' : 'Pending'}
        />
        <DataListItem
          label="Weekly Pricing"
          value="Generated by weekly cycle"
          meta="Your premium is produced by the backend weekly pricing run, not by a mobile checkout screen."
          tone="info"
          badgeLabel="Automatic"
        />
      </View>
    </ScreenShell>
  );
}
